runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app

- url: /
  static_files: ../frontend/build/index.html
  upload: ../frontend/build/index.html

- url: /
  static_dir: ../frontend/build


skip_files:
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?node_modules/
